### ISSUE TITLE
Screenshot bookmarks keep loading

### ISSUE THREAD

**Issue by Deca** [deweyapp/dewey#111]
I've about 120 bookmarks and are all stuck with the screenshot loading, I've keeped dewey opened for a couple of hour but nothing.
If in settings I uncheck the "show screenshot" option and return to the bookmarks list there is still a sort of header with the spinning loading animation.
Tested on windows 8.1 and Chrome  37.0.2062 , 38.x , Canary

**Comment by letraitplat** [comment]
Same here, kept opened but still loading
don't know how to check the code though, and I don't live in Italy but in France

great extension otherwise :)

**Comment by artemgrygor** [comment]
@Deca @letraitplat should be OK now. I close the issue.
