### ISSUE TITLE
My Fork

### ISSUE THREAD

**Issue by graehu** [deweyapp/dewey#113]
Hey Guys,

I forked your repo recently to make a personal website from it, mostly to learn some js/php stuff.
At the time I didn't realise that snapito was a paid api, partly because your chrome extension is free.

Due to this, I still have a bunch of links that use your api_key and I assume you'd want those removed.
I'm also going to remove your Google Analytics stuff for obvious reasons.

If you want to see the (hideous) website so far its: [graehu.com](http://graehu.com)
It's not really that different from the dewey app, it just uses server side databases instead of chrome storage.

Sorry to get in contact with you about this after I've started work. I didn't think I'd be able to get as much done as I did to be honest. (I'm a not a web developer by trade)

**Comment by outcoldman** [comment]
@graehu thank you for letting us know, and yes - please do not abuse our API and keys ;D
