### ISSUE TITLE
Screenshots not displaying (even after update)

### ISSUE THREAD

**Issue by jtenclay** [deweyapp/dewey#123]
Hi,
It seems like all the issues here about missing screenshots have been closed because the update was supposed to solve it. I downloaded the app about a week ago and unfortunately no screenshots have appeared yet. Show Screenshots is checked in Settings. Tried resetting, unchecking/rechecking the box, making new bookmarks, to no avail.

Running updated Chrome on Mac OSX Yosemite.

Thanks.

**Comment by hottehead** [comment]
+1 Screenshots not working
Even if I set it to not show screenshots there is still a loading icon in a small bar above the entry. That is annoying.

**Comment by scottferros** [comment]
+1 screenshots not working

**Comment by arnijohnsen** [comment]
+1 screenshots not working
Issue persists after waiting/reinstalling. Chrome Version 40.0.2214.93 m

**Comment by outcoldman** [comment]
We could not find any services which allow us to get screenshots for free :( 
If you know one - please send us pull request.

**Comment by arnijohnsen** [comment]
Is it not possible to take screenshots on client side, with html2canvas maybe?

**Comment by outcoldman** [comment]
@arnijohnsen I would guess that it can be slow. @arnijohnsen do you know how to do that, could you try it?

**Comment by arnijohnsen** [comment]
I'll have a check after finals :)

**Comment by letraitplat** [comment]
Hello
Same issue here, no screenshots :)
chrome 40.0.2214.111 m (64-bit)

**Comment by szarik88** [comment]
+1 for this issue. 
How's it going with this problem?

**Comment by sandygk** [comment]
same here

![image](https://cloud.githubusercontent.com/assets/6596836/6230022/19bd0f96-b6b4-11e4-947e-a3d599a2655e.png)

**Comment by sandygk** [comment]
I know this is a stupid question and that it's out of place but, what do you mean by +1? Is there an actual ranking sistems for the issues?

**Comment by outcoldman** [comment]
Folks, you are not helping. Please stop sending us "+1". This issue is open, all people on this thread is aware about this issue. We do not have an ability to fix it right now. 
Please read full thread, as I said

{quote}
We could not find any services which allow us to get screenshots for free :( 
If you know one - please send us pull request.
{quote}

So if you want to help - you can do that, fork this project, fix the issue, do the pull request. 

Thanks

**Comment by GoLocalApps** [comment]
Have you tried using embed.ly?

**Comment by pabloselli** [comment]
CORS !

 solution?

**Comment by xypaul** [comment]
+1

**Comment by pietmondrian** [comment]
@outcoldman it seems that most screenshot vendors have moved to a for-fee model.  Their pricing is transaction based (cache-based pulls for every 30-day period are free). Maybe your community of users might be willing to accelerate donations or pay a subscription fee to you.  I love your product - better than most out there - performance and clean UI are primary reason why I would be willing to pay.

**Comment by artemgrygor** [comment]
Should be fixed. I close this issue.

**Comment by pietmondrian** [comment]
@artemgrygor Thank you!  Fix works beautifully after uninstalling old version and installing your 3/11 version from Chrome store. Loaded 100 bookmarks in under a minute.

**Comment by pabloselli** [comment]
Thanks!
