### ISSUE TITLE
Screenshots: SOLUTION.

### ISSUE THREAD

**Issue by Shakarhaba** [deweyapp/dewey#131]
The problem
----------------
The problem is that the screenshots provider is no longer generating and returning the screenshots.

The solution
----------------
What I did to get it working again is simple, run my own screenshoot generator.

- Install wkhtmltopdf http://wkhtmltopdf.org/downloads.html
- Install Apache + PHP
       - Windows: Just install WAMP (Easy install: http://www.wampserver.com/en/)
       - Mac: (Easy install: MAMP: http://www.mamp.info/en/)
       - Ubuntu: apt-get install apache2, php5
- Enable headers apache module (a2enmod headers, in wamp use the menu from the system tray)
- Install/Enable curl if you want to check if the bookmark no longer exists
- In the www directory create a .htaccess file and folder called thumbnails
 
>**.htaccess content**
<pre>Header set Access-Control-Allow-Origin "*"
Header set Access-Control-Allow-Headers "Cache-Control, Pragma, Origin, Authorization, Content-Type, X-Requested-With"
Header set Access-Control-Allow-Methods "GET, PUT, POST"</pre>

5) Then download this gist: https://gist.github.com/Shakarhaba/2b9c6a9c0c3440d71951 and place it in www, call it index.php (you can rename it to whatever you want but you will have to edit updateBackground.js accordingly).

6) Edit the options if needed (You will have to set the path to the wkhtmltoimage binary at least).

7) Edit dewey/js/directive/updateBackground.js https://github.com/deweyapp/dewey/blob/master/js/directives/updateBackground.js

>**Point to localhost as the screenshot provider, and pass the url as a HTTP Post variable**
<pre>
37 - url: 'http://api.page2images.com/restfullink?p2i_url=' +
38 - encodeURIComponent(url) +
39 - &p2i_device=6&p2i_size=400x150&p2i_screen=1024x768&p2i_imageformat=jpg&p2i_wait=0&p2i_key=7cd903b37d087238',
37 + url: 'http://localhost',
38 + data: {url: url},
</pre>

Voilà, now you generate your own screenshots and you are no longer dependent of a third party screenshot providers that might leave you hanging in the near future.

As this solution works with apache + php you can place this on a web server on a NAS or a computer that it's always on, set up some DDNS and access your screenshots from any computer/device.

I love using Dewey, but I **NEED** the visual details from the screenshots so I had to edit it right away to get it working, at least until a new Screenshot provider is implemented.

**Comment by apple1314518** [comment]
how is this a SIMPLE solution?

**Comment by Shakarhaba** [comment]
It's installing a couple of things and adding 2 files for which I'm providing the content with a step-by-step guide, so from my point of view it seems pretty easy.

It's a temporary solution until a new provider is found.

**Comment by apple1314518** [comment]
it is over 7 multithreaded steps.

i'm not computer expert.  however, i just finished coding a visual
interactive ios app and i still can't follow the directions.  what does
install php/apache on a macbook mean?

if its temporary, when do you expect the general solution to come?

**Comment by Shakarhaba** [comment]
Easy install? http://www.mamp.info/en/

**Comment by apple1314518** [comment]
if your installation process involves me downloading a program that is not
listed in the installation process as one of 7 involved steps than it is
anything but easy.

2015-03-11 10:03 GMT-04:00 Shakarhaba <notifications@github.com>:

**Comment by Shakarhaba** [comment]
Google "Apache PHP mac": 3rd result is MAMP

**Comment by apple1314518** [comment]
just fix your program!!

**Comment by Shakarhaba** [comment]
Just as I imagened, you DON'T READ AT ALL. I'm not the developer dude.
I just presented this EASY TEMPORARY FIX until the developer finds some company that let's him generate screenshots, the program is not broken at all.

**Comment by apple1314518** [comment]
this is an easy fix

- go to preference and check box 3
- add file to users/important folder
-restart


THAT is easy.


if part of the first 5 stage process involves installing software from a
page of googled results it is NOT easy.

**Comment by artemgrygor** [comment]
Should be fixed. I close this issue.
