### ISSUE TITLE
Screenshot problem. Page2images account does not have enough credits.

### ISSUE THREAD

**Issue by artemgrygor** [deweyapp/dewey#134]
Hey guys,
@outcoldman @jamiewilson looks like we again have a problem with screenshots.
`"status":"error","msg":"Account does not have enough credits. Please login to our website www.page2images.com and check.","errno":403,"ori_url":"http:\/\/fb.com"}`

I've idea. Maybe we could cache screenshot and favicon?

**Comment by jamiewilson** [comment]
I sent a request in today to get bumped to the next tier so we'll have 200,000 api credits instead of 60,000.  Hopefully they see the ticket soon. But maybe we should look into caching options too?

**Comment by FJuri** [comment]
thumbnails are finally working for me! thanks!
