### ISSUE TITLE
Not allowed to load local resource

### ISSUE THREAD

**Issue by anshbansal** [deweyapp/dewey#135]
I keep a lot of local bookmarks. Mainly downloaded documentations or articles. But I am getting the error of not being able to load local resources.

I understand that this is due to security reasons. What I am suggesting is that local resources can be given a different treatement. I was going through the source code of another chrome extension neater-bookmarks which supports opening local resources. I found that they are using a anchor tag for the bookmarks. The relevant url is https://github.com/evanshultz/neater-bookmarks/blob/master/neat.js and the function is generateBookmarkHTML.

I have not checked this plugin's code but if it is not too much trouble then their approach may be better for opening bookmarks while yours has much better UI. Not only your UI but your search is also much better. 

If someone comments on this then maybe I can look more on this.

**Comment by anshbansal** [comment]
bump

**Comment by outcoldman** [comment]
@anshbansal honestly I do not understand where is the issue exactly? are we talking about favicons or screenshots?
