### ISSUE TITLE
Turning off screenshots does not disable loading icons

### ISSUE THREAD

**Issue by axefrog** [deweyapp/dewey#139]
I have no idea how repeatable this error is, but I just installed the Dewey app from the Chrome store, and the first thing I did was disable the screenshots. When I went back into card view though, all of the loading icons were still displaying and not going away. I have yet to completely kill the chrome process and start again, so I don't know if that will fix the problem, but I thought I'd report the initial problem anyway.

**Edit:** Confirmed. I restarted Chrome completely, and the loading icons are all still there. I'm guessing this is a bug.

![](http://content.screencast.com/users/NathanRidley/folders/Jing/media/fad160e9-9c61-4163-aea1-6d986772ebbe/2015-07-09_0733.png)

**Comment by matsair** [comment]
I have the same issue. Would be great, if we could get feedback on this.

**Comment by alebx** [comment]
+1

**Comment by Romainpetit** [comment]
:+1:

**Comment by pabloselli** [comment]
+1

**Comment by outcoldman** [comment]
I have deployed version 4.0.0 which is basically one big change - using our own screenshot generating server. Also I believe I have fixed this issue as well. 

If you want to help:
- As usual we will appreciate if you will contribute to code.
- Please consider donation https://github.com/deweyapp/dewey#donate - that will help us to switch to more powerful server. 
- If you like - please share http://deweyapp.io to your friends and followers.
