### ISSUE TITLE
How to start Dewey Bookmarks after many trials?

### ISSUE THREAD

**Issue by jackdashack** [deweyapp/dewey#172]
I'm not a newb, unless you consider only being on the web since 1996 a newb. I've added the extension. Restarted the chrome browser and can find no way to make Dewey Bookmarks even show let alone work? Is there some secret here I haven't asked for. Kidding. Just a little frustrated with myself that should see this clearly.

Thanks  Jack ";-\\

**Comment by outcoldman** [comment]
Hello Jack, as you can see the last checkin for this extension was made 4 years ago. It is not supported currently. Will not be surprised if it does not work at all.

**Comment by jackdashack** [comment]
Thank you. I am trying Sticky Passwords. Appreciate the info. ":-Dx
