### ISSUE TITLE
Open Links in new Tabs

### ISSUE THREAD

**Issue by MentalGear** [deweyapp/dewey#40]
Clicked bookmarks could open in a new tab (and switch to that new tab immediately).

Searches and scroll position within Dewey would remain, also you keep the user "in the app", and don't kick him out, e.g. more opportunity for him to further explore the app once he closed the clicked bookmark.
(otherwise he just closes the window when he's done with the bookmark and won't automatically return back to dewey)
This would also fix the issue #28.

"cmd" and click can be advised to open multiple bookmarks without switching to them.

I know some people like to use the same window and quickly go back with backspace when it wasn't the bookmark they were looking for, but as long as retain scroll and search is not available, this would at least be an excellent bridge solution. Not to mention for people who like to open multiple bookmarks.
Tell me what you think guys. :tada:

**Comment by zeckdude** [comment]
Was this added to the app? Cause I don't see it anywhere.
